package com.example.util;

public interface Steps {
    String REGISTERED = "REGISTERED";
    String ASK_CONTACT = "ASK_CONTACT";
    String ASK_CARD_NUMBER = "PAYMENT_ASK_CARD_NUMBER";
    String ASK_CARD_EXP = "ASK_CARD_EXP";
    String ASK_TO_JOIN_CHANNEL = "ASK_TO_JOIN_CHANNEL";
    String ASK_VERIFY_CODE = "ASK_VERIFY_CODE";
    String VERIFY_AND_PAY = "VERIFY_AND_PAY";
    String ASK_FULL_NAME = "ASK_FULL_NAME";
    String ASK_EMPLOYMENT_ACTIVITY = "ASK_EMPLOYMENT_ACTIVITY";
    String ASK_NUMBER_OF_EMPLOYEES = "ASK_NUMBER_OF_EMPLOYEES";
}