package com.example.util;

public interface Steps {

    String NEW_USER = "NEW_USER";
    String ASK_FULL_NAME = "ASK_FULL_NAME";
    String PHONE_NUMBER = "PHONE_NUMBER";
    String PHONE_NUMBER_ASK = "PHONE_NUMBER_ASK";
    String BUSINESS_TYPE = "BUSINESS_TYPE";
    String BUSINESS_TYPE_ASK = "BUSINESS_TYPE_ASK";
    String EMPLOYEE_COUNT = "EMPLOYEE_COUNT";
    String EMPLOYEE_COUNT_ASK = "EMPLOYEE_COUNT_ASK";
    String JOIN_CHANNEL = "JOIN_CHANNEL";
    String ASK_CARD_NUMBER = "ASK_CARD_NUMBER";
    String ASK_CARD_EXPIRE = "ASK_CARD_EXPIRE";
    String ASK_VERIFY_CODE = "ASK_VERIFY_CODE";
    String PAYMENT_FAIL = "PAYMENT_FAIL";
}
