package com.example.util;

public interface UserStep {
    String SAVE_CONTACT = "SAVE_CONTACT";
    String ASK_FULL_NAME = "ASK_FULL_NAME";
    String ASK_EMPLOYMENT_ACTIVITY = "ASK_EMPLOYMENT_ACTIVITY";
    String ASK_EMPLOYEE_COUNT = "ASK_EMPLOYEE_COUNT";
    String SHOW_CHANNEL = "SHOW_CHANNEL";
    String ASK_CARD_NUMBER = "ASK_CARD_NUMBER";
    String ASK_CARD_EXPIRY_DATE = "ASK_CARD_EXPIRY_DATE";
    String ASK_VERIFICATION_CODE = "ASK_VERIFICATION_CODE";
    String DEFAULT = "DEFAULT";
    String PREMIUM = "PREMIUM";
    String ADMIN_MAIN_MENU = "ADMIN_MAIN_MENU";
}
